# -*- coding: utf-8 -*-
"""3_multi class.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d8QMD1sXTFVU4VpI1krN0Tw8FQ2-l4SZ

#  다중 클래스 분류
"""

#  이진 분류 알고리즘을 소프트맥스를 사용해 one vs all(rest)로 확장 시킬 수 있다.

from sklearn.datasets import load_breast_cancer
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

cancer = load_breast_cancer()

X_train, X_test, y_train, y_test = train_test_split(cancer.data, 
                                                    cancer.target, 
                                                    stratify=cancer.target, 
                                                    random_state=42)
tree = DecisionTreeClassifier(random_state = 0)

# stratify 레이블이 불균형할때  계층을 맞춰서 나눠주는 기능.
tree.fit(X_train, y_train)

print("훈련 세트 정확도 : {:.3f}".format(tree.score(X_train, y_train)))
print("테스트 세트 정확도 : {:.3f}".format(tree.score(X_test, y_test)))

#  사전  가지치기를 적용한 의사결정나무
tree = DecisionTreeClassifier(max_depth =4, random_state = 0)
tree.fit(X_train, y_train)

print("훈련 세트 정확도 : {:.3f}".format(tree.score(X_train, y_train)))
print("테스트 세트 정확도 : {:.3f}".format(tree.score(X_test, y_test)))

