# -*- coding: utf-8 -*-
"""3_random_forest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rehfjNTJqzC2eebrCY2czSnaNG8a-XRd
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split

X, y = make_moons(n_samples=100, noise=0.25, random_state=3)
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=42)

#  랜덤 포레스트를 구성할 의사결정 나무의 개수를 5개로 지정, random_state -> 부트스트랩 샘플링 랜덤 고정.
forest = RandomForestClassifier(n_estimators=5, random_state=2)
forest.fit(X_train, y_train)

print("훈련 세트 점수 :  {:.3f}".format(forest.score(X_train, y_train)))
print("테스트 세트 점수 :  {:.3f}".format(forest.score(X_test, y_test)))

# 사용된 나무의 정보.
forest.estimators_

