# -*- coding: utf-8 -*-
"""9_1_loadMNIST.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D14mQbHu8mW-JwaoOr5PmHxXPcpxeVfc
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf
# %matplotlib inline

"""# MNIST Loading 및 시각화"""

from tensorflow.keras import datasets
mnist = datasets.mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train.shape

"""[개수, 높이, 너비]"""

# 첫번째 이미지 불러오기
image = X_train[0]
image.shape

# 첫번째 이미지의 정답 확인하기
y_train[0]

"""내가 사용하고자 하는 이미지가 GrayScale이면 채널을 1로 설정, RGB면 채널을 3으로 설정"""

X_train.shape

"""위 데이터는 채널 정보가 없기 때문에 tensorflow훈련 데이터로 사용 불가능

[개수, 높이, 너비] -> [개수, 높이, 너비, 채널]

그런데 RGB데이터를 불러온 경우 알아서 채널이 들어가 있다.
"""

new_X_train = X_train[..., tf.newaxis]
new_X_train.shape

new_train_image = new_X_train[0, :, :, 0]
new_train_image.shape

plt.imshow(new_train_image, 'gray')
plt.show()

new_train_image_squeeze = tf.squeeze(new_X_train[0])
new_train_image_squeeze.shape

plt.imshow(new_train_image_squeeze, 'gray')
plt.show()

